apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-bubliny-appka
  namespace: openshift-gitops
spec:
  destination:
    namespace: namespace1
    server: https://kubernetes.default.svc
  project:  default
  source:
    path: ./
    repoURL: https://github.com/mjankula/bubliny-appka.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

